server:
  port: 8080

eureka:
  instance:
    hostname: 192.168.41.90
    prefer-ip-address: true
  client:
    #是否要注册到eureka
    registerWithEureka: false
    #表示是否从Eureka Server获取注册信息
    fetchRegistry: false
    #单机配置
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/